/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsoRouteImport } from './routes/uso'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as LivrosRouteImport } from './routes/livros'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as DefinicoesRouteImport } from './routes/definicoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as StudioUploadRouteImport } from './routes/studio.upload'
import { Route as StudioPlaylistsRouteImport } from './routes/studio.playlists'
import { Route as StudioOnboardingRouteImport } from './routes/studio.onboarding'
import { Route as StudioContentRouteImport } from './routes/studio.content'
import { Route as StudioAnalyticsRouteImport } from './routes/studio.analytics'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as AuthBridgeRouteImport } from './routes/auth.bridge'

const UsoRoute = UsoRouteImport.update({
  id: '/uso',
  path: '/uso',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrosRoute = LivrosRouteImport.update({
  id: '/livros',
  path: '/livros',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinicoesRoute = DefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioUploadRoute = StudioUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPlaylistsRoute = StudioPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => StudioRoute,
} as any)
const StudioOnboardingRoute = StudioOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => StudioRoute,
} as any)
const StudioContentRoute = StudioContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAnalyticsRoute = StudioAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => StudioRoute,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthBridgeRoute = AuthBridgeRouteImport.update({
  id: '/auth/bridge',
  path: '/auth/bridge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/definicoes': typeof DefinicoesRoute
  '/explorar': typeof ExplorarRoute
  '/home': typeof HomeRoute
  '/livros': typeof LivrosRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRouteWithChildren
  '/uso': typeof UsoRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/post/$id': typeof PostIdRoute
  '/studio/analytics': typeof StudioAnalyticsRoute
  '/studio/content': typeof StudioContentRoute
  '/studio/onboarding': typeof StudioOnboardingRoute
  '/studio/playlists': typeof StudioPlaylistsRoute
  '/studio/upload': typeof StudioUploadRoute
  '/u/$username': typeof UUsernameRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/definicoes': typeof DefinicoesRoute
  '/explorar': typeof ExplorarRoute
  '/home': typeof HomeRoute
  '/livros': typeof LivrosRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/uso': typeof UsoRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/post/$id': typeof PostIdRoute
  '/studio/analytics': typeof StudioAnalyticsRoute
  '/studio/content': typeof StudioContentRoute
  '/studio/onboarding': typeof StudioOnboardingRoute
  '/studio/playlists': typeof StudioPlaylistsRoute
  '/studio/upload': typeof StudioUploadRoute
  '/u/$username': typeof UUsernameRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/definicoes': typeof DefinicoesRoute
  '/explorar': typeof ExplorarRoute
  '/home': typeof HomeRoute
  '/livros': typeof LivrosRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRouteWithChildren
  '/uso': typeof UsoRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/post/$id': typeof PostIdRoute
  '/studio/analytics': typeof StudioAnalyticsRoute
  '/studio/content': typeof StudioContentRoute
  '/studio/onboarding': typeof StudioOnboardingRoute
  '/studio/playlists': typeof StudioPlaylistsRoute
  '/studio/upload': typeof StudioUploadRoute
  '/u/$username': typeof UUsernameRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/definicoes'
    | '/explorar'
    | '/home'
    | '/livros'
    | '/mensagens'
    | '/perfil'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/studio'
    | '/uso'
    | '/auth/bridge'
    | '/post/$id'
    | '/studio/analytics'
    | '/studio/content'
    | '/studio/onboarding'
    | '/studio/playlists'
    | '/studio/upload'
    | '/u/$username'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/definicoes'
    | '/explorar'
    | '/home'
    | '/livros'
    | '/mensagens'
    | '/perfil'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/uso'
    | '/auth/bridge'
    | '/post/$id'
    | '/studio/analytics'
    | '/studio/content'
    | '/studio/onboarding'
    | '/studio/playlists'
    | '/studio/upload'
    | '/u/$username'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/definicoes'
    | '/explorar'
    | '/home'
    | '/livros'
    | '/mensagens'
    | '/perfil'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/studio'
    | '/uso'
    | '/auth/bridge'
    | '/post/$id'
    | '/studio/analytics'
    | '/studio/content'
    | '/studio/onboarding'
    | '/studio/playlists'
    | '/studio/upload'
    | '/u/$username'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DefinicoesRoute: typeof DefinicoesRoute
  ExplorarRoute: typeof ExplorarRoute
  HomeRoute: typeof HomeRoute
  LivrosRoute: typeof LivrosRoute
  MensagensRoute: typeof MensagensRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  StudioRoute: typeof StudioRouteWithChildren
  UsoRoute: typeof UsoRoute
  AuthBridgeRoute: typeof AuthBridgeRoute
  PostIdRoute: typeof PostIdRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uso': {
      id: '/uso'
      path: '/uso'
      fullPath: '/uso'
      preLoaderRoute: typeof UsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livros': {
      id: '/livros'
      path: '/livros'
      fullPath: '/livros'
      preLoaderRoute: typeof LivrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definicoes': {
      id: '/definicoes'
      path: '/definicoes'
      fullPath: '/definicoes'
      preLoaderRoute: typeof DefinicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/upload': {
      id: '/studio/upload'
      path: '/upload'
      fullPath: '/studio/upload'
      preLoaderRoute: typeof StudioUploadRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/playlists': {
      id: '/studio/playlists'
      path: '/playlists'
      fullPath: '/studio/playlists'
      preLoaderRoute: typeof StudioPlaylistsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/onboarding': {
      id: '/studio/onboarding'
      path: '/onboarding'
      fullPath: '/studio/onboarding'
      preLoaderRoute: typeof StudioOnboardingRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/content': {
      id: '/studio/content'
      path: '/content'
      fullPath: '/studio/content'
      preLoaderRoute: typeof StudioContentRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/analytics': {
      id: '/studio/analytics'
      path: '/analytics'
      fullPath: '/studio/analytics'
      preLoaderRoute: typeof StudioAnalyticsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/bridge': {
      id: '/auth/bridge'
      path: '/auth/bridge'
      fullPath: '/auth/bridge'
      preLoaderRoute: typeof AuthBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteChildren {
  StudioAnalyticsRoute: typeof StudioAnalyticsRoute
  StudioContentRoute: typeof StudioContentRoute
  StudioOnboardingRoute: typeof StudioOnboardingRoute
  StudioPlaylistsRoute: typeof StudioPlaylistsRoute
  StudioUploadRoute: typeof StudioUploadRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioAnalyticsRoute: StudioAnalyticsRoute,
  StudioContentRoute: StudioContentRoute,
  StudioOnboardingRoute: StudioOnboardingRoute,
  StudioPlaylistsRoute: StudioPlaylistsRoute,
  StudioUploadRoute: StudioUploadRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DefinicoesRoute: DefinicoesRoute,
  ExplorarRoute: ExplorarRoute,
  HomeRoute: HomeRoute,
  LivrosRoute: LivrosRoute,
  MensagensRoute: MensagensRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StudioRoute: StudioRouteWithChildren,
  UsoRoute: UsoRoute,
  AuthBridgeRoute: AuthBridgeRoute,
  PostIdRoute: PostIdRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
