/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsoRouteImport } from './routes/uso'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as LivrosRouteImport } from './routes/livros'
import { Route as HomeRouteImport } from './routes/home'
import { Route as Hdequipa9x2RouteImport } from './routes/hdequipa9x2'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as DropsRouteImport } from './routes/drops'
import { Route as DefinicoesRouteImport } from './routes/definicoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as AuthBridgeRouteImport } from './routes/auth.bridge'

const UsoRoute = UsoRouteImport.update({
  id: '/uso',
  path: '/uso',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrosRoute = LivrosRouteImport.update({
  id: '/livros',
  path: '/livros',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const Hdequipa9x2Route = Hdequipa9x2RouteImport.update({
  id: '/hdequipa9x2',
  path: '/hdequipa9x2',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsRoute = DropsRouteImport.update({
  id: '/drops',
  path: '/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinicoesRoute = DefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthBridgeRoute = AuthBridgeRouteImport.update({
  id: '/auth/bridge',
  path: '/auth/bridge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/definicoes': typeof DefinicoesRoute
  '/drops': typeof DropsRoute
  '/explorar': typeof ExplorarRoute
  '/hdequipa9x2': typeof Hdequipa9x2Route
  '/home': typeof HomeRoute
  '/livros': typeof LivrosRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/uso': typeof UsoRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/post/$id': typeof PostIdRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/definicoes': typeof DefinicoesRoute
  '/drops': typeof DropsRoute
  '/explorar': typeof ExplorarRoute
  '/hdequipa9x2': typeof Hdequipa9x2Route
  '/home': typeof HomeRoute
  '/livros': typeof LivrosRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/uso': typeof UsoRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/post/$id': typeof PostIdRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/definicoes': typeof DefinicoesRoute
  '/drops': typeof DropsRoute
  '/explorar': typeof ExplorarRoute
  '/hdequipa9x2': typeof Hdequipa9x2Route
  '/home': typeof HomeRoute
  '/livros': typeof LivrosRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/uso': typeof UsoRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/post/$id': typeof PostIdRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/definicoes'
    | '/drops'
    | '/explorar'
    | '/hdequipa9x2'
    | '/home'
    | '/livros'
    | '/mensagens'
    | '/perfil'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/studio'
    | '/uso'
    | '/auth/bridge'
    | '/post/$id'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/definicoes'
    | '/drops'
    | '/explorar'
    | '/hdequipa9x2'
    | '/home'
    | '/livros'
    | '/mensagens'
    | '/perfil'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/studio'
    | '/uso'
    | '/auth/bridge'
    | '/post/$id'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/definicoes'
    | '/drops'
    | '/explorar'
    | '/hdequipa9x2'
    | '/home'
    | '/livros'
    | '/mensagens'
    | '/perfil'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/studio'
    | '/uso'
    | '/auth/bridge'
    | '/post/$id'
    | '/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DefinicoesRoute: typeof DefinicoesRoute
  DropsRoute: typeof DropsRoute
  ExplorarRoute: typeof ExplorarRoute
  Hdequipa9x2Route: typeof Hdequipa9x2Route
  HomeRoute: typeof HomeRoute
  LivrosRoute: typeof LivrosRoute
  MensagensRoute: typeof MensagensRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  StudioRoute: typeof StudioRoute
  UsoRoute: typeof UsoRoute
  AuthBridgeRoute: typeof AuthBridgeRoute
  PostIdRoute: typeof PostIdRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uso': {
      id: '/uso'
      path: '/uso'
      fullPath: '/uso'
      preLoaderRoute: typeof UsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livros': {
      id: '/livros'
      path: '/livros'
      fullPath: '/livros'
      preLoaderRoute: typeof LivrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hdequipa9x2': {
      id: '/hdequipa9x2'
      path: '/hdequipa9x2'
      fullPath: '/hdequipa9x2'
      preLoaderRoute: typeof Hdequipa9x2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops': {
      id: '/drops'
      path: '/drops'
      fullPath: '/drops'
      preLoaderRoute: typeof DropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definicoes': {
      id: '/definicoes'
      path: '/definicoes'
      fullPath: '/definicoes'
      preLoaderRoute: typeof DefinicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/bridge': {
      id: '/auth/bridge'
      path: '/auth/bridge'
      fullPath: '/auth/bridge'
      preLoaderRoute: typeof AuthBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DefinicoesRoute: DefinicoesRoute,
  DropsRoute: DropsRoute,
  ExplorarRoute: ExplorarRoute,
  Hdequipa9x2Route: Hdequipa9x2Route,
  HomeRoute: HomeRoute,
  LivrosRoute: LivrosRoute,
  MensagensRoute: MensagensRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StudioRoute: StudioRoute,
  UsoRoute: UsoRoute,
  AuthBridgeRoute: AuthBridgeRoute,
  PostIdRoute: PostIdRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
