// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

// Evita disparar vários refreshSession() em paralelo quando várias
// chamadas falham ao mesmo tempo por token expirado.
let refreshPromise: Promise<unknown> | null = null;

async function refreshAuthSessionOnce(): Promise<void> {
  if (!refreshPromise) {
    refreshPromise = _supabase!.auth.refreshSession().finally(() => {
      refreshPromise = null;
    });
  }
  await refreshPromise;
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  const doFetch = (input: RequestInfo | URL, init?: RequestInit) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };

  return async (input, init) => {
    const response = await doFetch(input, init);

    // O token de sessão pode expirar em segundo plano (ex: aba ficou
    // minimizada/inativa e o refresh automático do Supabase não teve
    // chance de correr a tempo). Sem isto, o pedido falha com 401 "JWT
    // expired" e o conteúdo (posts, mensagens, etc.) some da tela até a
    // pessoa recarregar a página. Aqui detetamos esse caso, renovamos a
    // sessão uma vez e repetimos o pedido original automaticamente.
    if (response.status === 401 && _supabase) {
      let isExpiredJwt = false;
      try {
        const cloned = response.clone();
        const body = await cloned.text();
        isExpiredJwt = body.includes('JWT expired') || body.includes('PGRST303');
      } catch {
        // ignora — se não conseguirmos ler o corpo, seguimos sem retry
      }

      if (isExpiredJwt) {
        try {
          await refreshAuthSessionOnce();
          const { data } = await _supabase.auth.getSession();
          const freshToken = data.session?.access_token;
          if (freshToken) {
            const retryHeaders = new Headers(
              typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
            );
            if (init?.headers) {
              new Headers(init.headers).forEach((value, key) => retryHeaders.set(key, value));
            }
            retryHeaders.set('Authorization', `Bearer ${freshToken}`);
            return doFetch(input, { ...init, headers: retryHeaders });
          }
        } catch {
          // Se o refresh falhar (ex: sessão realmente inválida), devolve
          // a resposta 401 original — o AuthContext vai tratar o logout.
        }
      }
    }

    return response;
  };
}


function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

